name: Test Old TypeScript

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: yarn install --frozen-lockfile --check-files
      - name: Test Build # we don't have any other workflows to test build
        run: yarn build
      - name: Test Default
        run: yarn test:ci

  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        typescript:
          - 4.8
          - 4.7
          - 4.6
          - 4.5
          - 4.4
          - 4.3
          - 4.2
          - 4.1
          - 4.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: yarn install --frozen-lockfile --check-files
      - name: Patch for Old TS
        if: ${{ matrix.typescript < 4.4 }}
        run: |
          sed -i~ "s/\/\/ @ts-expect-error.*\[LATEST-TS-ONLY\]//" tests/*.tsx
          sed -i~ "s/\"exactOptionalPropertyTypes\": true,//" tsconfig.json
      - name: Test ${{ matrix.typescript }}
        run: |
          yarn add -D typescript@${{ matrix.typescript }}
          yarn test:ci
